import { GetServerSidePropsContext } from 'next';
import Head from 'next/head';
import Hero from '../components/home/Hero';
import {getSelectorsByUserAgent} from 'react-device-detect';
import TeachProcess from '../components/home/teach-process/teach-process';
import Events from '../components/thematic-events/events';

export default function Home({ isMobileOnly, isTablet, isDesktop }: any) {
    
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Hero isMobileOnly={isMobileOnly} />
            <TeachProcess />
            <Events isMobileOnly={isMobileOnly} isTablet={isTablet} isDesktop={isDesktop} />
        </>
    );
}
export async function getServerSideProps({ req, res }: GetServerSidePropsContext) {
    const userAgent = req.headers['user-agent'] || '';
    const { isMobileOnly, isTablet, isDesktop  } = getSelectorsByUserAgent(userAgent);

    return {
        props: { isMobileOnly, isTablet, isDesktop },
    };
}